# Generated by Django 5.0.2 on 2024-03-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='futebolarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('SP', 'SÃO PAULO'), ('RJ', 'RIO DE JANEIRO'), ('PI', 'PIAUÍ')], max_length=120, null=True)),
                ('cores', models.CharField(blank=True, max_length=80, null=True)),
                ('ano_fundacao', models.PositiveIntegerField(default=0)),
                ('tem_mundial', models.BooleanField(default=False)),
            ],
        ),
    ]
