# Generated by Django 5.0.2 on 2024-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ano_fundacao_clube_ano_de_fundacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('E', 'ESTADUAL'), ('N', 'NACIONAL'), ('I', 'INTERNACIONAL')], max_length=80, null=True)),
                ('categoria', models.CharField(choices=[('CP', 'COPA'), ('CAMP', 'CAMPEONATO')], max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_da_conquista', models.PositiveIntegerField(default=0)),
                ('data_exata', models.DateField(blank=True, null=True)),
                ('colocacao', models.CharField(choices=[('1º', 'CAMPEÃO'), ('2ª', 'VICE')], max_length=80, null=True)),
            ],
            options={
                'verbose_name_plural': 'TÍTULOS',
            },
        ),
        migrations.AlterModelOptions(
            name='clube',
            options={'verbose_name_plural': 'CLUBES'},
        ),
    ]
