# Generated by Django 5.0.2 on 2024-03-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comuns', '0001_initial'),
        ('core', '0006_remove_clube_cidade_remove_clube_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comuns.cidade'),
        ),
        migrations.AddField(
            model_name='clube',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comuns.estado'),
        ),
        migrations.AddField(
            model_name='clube',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Comuns.pais'),
        ),
    ]
