# Generated by Django 5.0.2 on 2024-03-05 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clube_cidade_clube_estado_clube_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='nome',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='colocacao',
            field=models.ForeignKey(choices=[('1º', 'CAMPEÃO'), ('2ª', 'VICE')], max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
    ]
