# Generated by Django 5.0.2 on 2024-03-06 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_competicao_nome_alter_titulo_colocacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clube'),
        ),
    ]
